#! /bin/bash

LINK_WEB1="http://api.flickr.com/services/rest/"
LINK_WEB2="?method=flickr.interestingness.getList&api_key=ed6204a240a139921dbbc30c1a1e6f65&date="
LINK_WEB3="&extras=owner_name%2Cviews&per_page=500&format=rest"
LINK_FILE3="&extras=owner_name,views&per_page=500&format=rest"
FILE_PREFIX="best_photos_"
FILE_SUFIX=".xml"
LOG_FILE="data-sources.txt"

for MONTH in 04
do
  for DAY in 30 #29 28 27 26 25 24 23 22 21 20 19 18 17
  do 
    DATE=2012-$MONTH-$DAY
    LINK=$LINK_WEB1$LINK_WEB2$DATE$LINK_WEB3
    LINK_FILE=index.html$LINK_WEB2$DATE$LINK_FILE3
    FILE=$FILE_PREFIX$DATE$FILE_SUFIX
    wget $LINK
    mv $LINK_FILE api_original/api_$FILE
    echo $FILE $LINK >> $LOG_FILE
    xsltproc --stringparam DATE $DATE xslt/api_best_photos.xslt api_original/api_$FILE > $FILE
  done
done
